### ISSUE TITLE
create config.php

### ISSUE THREAD

**Issue by mf0hka** [elabftw/elabctl#1]
Due to installation woes, I tried the wget install method. 
I am unfamiliar with mariadb, and nginx, and despite having run successfully, there are still database issues. Actualy, why doesnt the fresh drop create the appropriate config.php instead of a config.php-example? I mean, its setting up the user and database anyway, why not just have it create the appropraite configfile as part of the install?

anyhow, trying to use the wget drop was unsuccessfull. The log file seems to think it created a elabftw user, but my database says no such userexists.

**Comment by NicolasCARPi** [comment]
Hello,
Did you try this on a fresh drop ? I mean a new server from digitalocean.com ?
It works only on a fresh drop.

And it doesn't create the config.php file because you want to visit the /install page which will load the SQL structure into the database. But that can be further streamlined, it's true.

**Comment by NicolasCARPi** [comment]
I'm surprised you encounter such troubles, the install works fine normally.
