### ISSUE TITLE
Backup file sizes

### ISSUE THREAD

**Issue by mjeltsch** [elabftw/elabctl#13]
My lab has now been using elabFTW for quite a while and it seems, that the size of the backup files does not increase in a linear fashion, but somehow exponentially (maybe its also that people use it differently and thus bigger backup files are produced). The present backup script is not very disk space friendly and I have forked the elabctl project and have added a snapshot command to elabctl that uses rsync to make incremental, uncompressed backups. After the first backup (which is larger than a compressed backup), any incremental backup uses much less disk space and is also is faster. However, the biggest issue is the experiments_revisions table, which is still need to address since the incrementals that I use are at the file level (and once can only mysqldump whole tables, but not deltas). I am going to test my first release soon on our production system (we started to get complaints from the IT guys that our backups fill the hard drive or the VM).

**Comment by NicolasCARPi** [comment]
Yes, the backup command is pretty crude and not incremental at all. But the backup should not be stored in the VM but on a file server with Tb of free space! :p Unless you keep old backups, it should not take more than a few Gb at most. And instead of making a zip of the uploaded files, you can just rsync the folder to another place and be done (this way you only have 2n in total size).

As for the experiments_revisions, it's only text, so I don't see the issue here. Even if you have one million of entries in there, it should still be in the Mb range.

**Comment by mjeltsch** [comment]
Attached is the reason why I am worried. I know that the big increase is from the experiments_revisions table, but I need to investigate further what specifically does cause the recent exponential growth. We do backup to a cheap file server with many TBs.
[size-development.pdf](https://github.com/elabftw/elabctl/files/1634747/size-development.pdf)

**Comment by NicolasCARPi** [comment]
Oh I see! Indeed it's a scary curve :D 

The revisions table gets populated upon a Save action. Maybe it's a bit too much, and maybe a revision shouldn't be added if the previous save time is too close…

**Comment by mjeltsch** [comment]
Hi Nicolas,
I am just investigating and one of our new lab members seems to save very
frequently. Different people have different habits of how often they hit
the save button and one should not boss them around for their habits. But
when they save, they obviously expect this to have an effect.

The issue seems to be with images, but I have no clue how they end up in
the body field of the experiments_revisions. But if they do, every single
click of the save button can add significant amounts of data depending on
the image size.

In the case that I investigate at the moment it is a 1.9MB png file that is
saved inside the body of the experiments_revisions table (<img
src="data:image/png;base64, followed by the image data; attached to this
e-mail). I know that the users have been experimenting with image import,
because they are not satisfied with the current options. They would like to
embed tif images into the text but when they are uploaded, the "Insert in
text at cursor position" is not available for them, although most of our
scientific devices, that produce images are producing them as tifs and that
requires from them to open them first in a third party program to convert
them to PNG or JPG to be able to make them fully useful for elabftw.

If I understood you, the image data itself should never end up inside the
body text, correct?

Cheers,
Michael

**Comment by NicolasCARPi** [comment]
Ok I see. The issue here is that the images are modified within tinymce, and saved as base64 in the text. If the image is only imported normally, it'll just be a link to the uploaded file and not take much space. Same if only the size is changed. But if you start playing with other options from the image editing menu, it'll get saved as base64.

The TIFF file format is not as easy to deal with as with jpg, gif or png. This is why I had to use a different library to make TIFF thumbnails. I understand that you work with tiff files (I do too), but for the lab notebook you should export a jpg if you wish to add it in the text (it's still fine to upload it and just reference it from the text, you don't have to absolutely put it inside the text!!!).

All over the web, you'll not find one image that is in tif. Everything is in jpg, png or gif. There are reasons for that. eLab being on the web, the same rules apply.

Again, I want to stress out that you don't have to systematically import the images in the text. Why not say "see attached image" in the text instead.

Also, eLab is a lab notebook, not an image editor. There is already a few options to play with images, and users always want more. But let's be clear: if you want to edit images, you open it in an image editor (fiji/imagej) and you do the job with the right tool. Then you export a nice (and lightweight) jpg and if you want, you put that in the experiment report.

That's how I see things.

So for your use case, just ask your users to stop fiddling with images after importing them, or they get stored in base64 and it takes much more space than reasonable. If they want to modify images, they should use an image editor, end of story.

Regards,
~Nico

**Comment by mjeltsch** [comment]
Thanks for your rapid answer!

I personally tend to agree with your viewpoint. However, when trying
convince people to use elabftw, issues like the tif placement into the body
and "do not use the inbuilt image editor" do generate "no-way I am going to
use this software" responses. Even in my lab, I have not been able to
convince everybody to use elabFTW (I am not the boss that forces people
into a specific work flow; I try to honor academic freedom).

I think listening to the real users is important (and from the 200
experiments that are in our elabFTW, only 4 are mine) and preferably
software should solve the tif import and TinyMCE image editing issues as
opposed to telling people what to do. Apple famously has been accusing
their users of "wrongly" using their products instead of listening to
complaints...

If there was a switch to disable image editing in TinyMCE, that would at
least prevent the size increase issue from happening... And why not to
convert every uploaded image first into png (or jpg) and then using the
result for generating thumbnails and everything else? Such preprocessing
could enable in the long run support for many more image formats that
people might desire (and some open source programs do use a preprocessor to
unify different file formats from scientific devices into one standard,
e.g. the Staden package). For us it is the various phosphoimagers (Fuji,
GE) that output images in formats that we need to convert at the moment in
any case before uploading to elabftw. However, gimp or ImageJ can open all
of them, hence I assume that some open code exists for these formats. I am
aware that this requires a massive amount of re-wiring the code.

I will follow now how the size usage of our backups grow without asking
users for habit changes. I do no win parallel a daily backup and a snapshot
and will compare their disk usage after a few weeks. Time permitting, I
also will check whether there is an easy way to avoid multiple backing up
the same embedded images (because they do change much less than the text
around them). The experiments_revisions table would still grow relatively
fast. Also loading pages with embedded images appears much slower than
pages with linked images...

So much for now!

Cheers,
Michael



Dr. Michael Jeltsch, group leader
Wihuri Research Institute & Translational Cancer Biology Program
University of Helsinki
Haartmaninkatu 8 (Biomedicum Helsinki)
FIN-00014 Helsinki
+358-2941-25514 (work)
+358-50-3200235 (mobile)
michael@jeltsch.org
http://lab.jeltsch.org
http://jeltsch.org

Follow my lab's page at Google+
<https://plus.google.com/+TheJeltschLaboratoryHelsinki> or Facebook
<https://www.facebook.com/TheJeltschLaboratory/>

**Comment by NicolasCARPi** [comment]
I agree with you that's it's important to listen to the users, and that's what I try to do as much as possible with this project. If I can do it, I'll do it. Contributions are welcome ;)
