### ISSUE TITLE
mysqldump error after upgrade to elabctl v 2.3.3

### ISSUE THREAD

**Issue by ChrisHal** [elabftw/elabctl#23]
When I do a backup via ``elabctl backup`` I get this error (but backup seems to proceed anyway):
```
mysqldump: [ERROR] unknown variable 'column-statistics=0'
```

**Comment by NicolasCARPi** [comment]
Yes, that is a recent change related to https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109

What version of mysqldump do you have? (`docker exec -it mysql mysqldump --version`)

**Comment by ChrisHal** [comment]
I get:
``mysqldump  Ver 10.13 Distrib 5.7.37, for Linux (x86_64)``

**Comment by NicolasCARPi** [comment]
Interesting, because you're using version 10 and this change is for version 8. Did they revert it for version 10?? Anyway, I think I'll just revert this change. Be careful that your backup file is probably empty, it's not because the file is created that the backup succeded! (hence the importance of actually testing backups!).

**Comment by ChrisHal** [comment]
Thank you :-)
