### ISSUE TITLE
issues with automated letsencrypt

### ISSUE THREAD

**Issue by rawray7** [elabftw/elabctl#3]
i just tried the automated install on a couple of fresh Ubuntu 14.04.4 x64 droplets, with both versions of the instructions. i thought i'd document my findings to help make this even smoother/easier for others.

i could not get this script to work (from latest):

`wget -qO- https://get.elabftw.net|sh`

this script (from next) did eventually work for me, with the caveats below:

`wget -qO- https://get.elabftw.net > install-elabftw.sh && sh install-elabftw.sh`

my letsencrypt failed a few times because i had a very small terminal window, this is a known issue: https://github.com/certbot/certbot/issues/2787

i only succeeded in getting the 'standalone' version (option 2 in the letsencrypt dialog) working. the webroot version failed for me, but perhaps i messed that up. if someone can get that working, more explicit instructions would be helpful.

it might also be helpful if the script was able to check for a successful letsencrypt install. if that fails, all of the elabftw install messages point to success - which is slightly confusing. not sure how involved that would be to implement.

this script is a really powerful tool - i'm really glad you are working to making elabftw even easier to install!

**Comment by NicolasCARPi** [comment]
Hello,

The piping directly does NOT work, that's for sure. Latest is in fact not latest version... Latest version is default version.

I realize now that they changed how letsencrypt works, hence the documentation is dated. Indeed I could also make it work with option 2 (and option 1 failed). I think option 1 fails because the webserver is stopped at that time. This would be easy to fix.

As you can see on line 5 of [this file](https://github.com/elabftw/drop-elabftw/blob/dropcker/drop-elabftw.sh), the next version of the script, it will stop if there is a fail. Also, in the next version it will use docker.

Finally, I realize that you need to take Ubuntu 16.04 because on 14.04 php is outdated! Next elabftw version requires 5.6 at least.
In the next version of the documentation, I'll ask users to take the Docker image. At the moment I don't have letsencrypt working with docker, some work is still needed.

Thanks for your input!

**Comment by NicolasCARPi** [comment]
Hello,

I've made the changes necessary to use letsencrypt.
If you try again a fresh install by following this doc : http://elabftw.readthedocs.io/en/hypernext/install-drop.html it should go smoothly :)

**Comment by rawray7** [comment]
now this is magical!

**Comment by NicolasCARPi** [comment]
Cheers \o/
